[monitor]
monitor-server ansible_host=monitor-server
[web]
web-server ansible_host=web-server
[db]
db-server ansible_host=db-server
[all_managed:children]
monitor
web
db
# Variables que se aplican a todos los hosts
[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
